
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      # sam build 
      - run: Build
        working-directory: ./src/s3
      - name: Package
        #if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
        working-directory: ./src/s3
        run: |
          sam package \
            --s3-bucket juanfunctions \
            --s3-prefix s3 \
            --output-template-file packaged.yaml
      - name: Store
        #if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
        uses: actions/upload-artifact@v3
        with:
          name: s3-packaged.yaml
          path: src/s3/packaged.yaml

