
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            s3:
              - 'src/s3/**'
      - if: steps.changes.outputs.s3 == 'true'
        uses: actions/checkout@v2
      - if: steps.changes.outputs.s3 == 'true'
        uses: aws-actions/setup-sam@v1
      - if: steps.changes.outputs.s3 == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - if: steps.changes.outputs.s3 == 'true'
        name: Build
        run: sam build --use-container
        working-directory: ./src/s3
      - if: steps.changes.outputs.s3 == 'true'
        name: Package
        working-directory: ./src/s3
        run: |
          sam package \
             --s3-bucket juanfunctions \
             --s3-prefix s3 \
             --output-template-file packaged.yaml
      - if: steps.changes.outputs.s3 == 'true'
        name: Publish
        run: sam publish --template packaged.yaml
        working-directory: ./src/s3
      - if: steps.changes.outputs.s3 == 'true'
        name: Store
        working-directory: ./src/s3
        run: |
          aws s3 cp \
            $(yq -r '.Resources | to_entries | .[] | select(.key == "LambdaLayer" or .key == "LambdaFunction") | .value.Properties | to_entries | .[] | select(.key == "ContentUri" or .key == "CodeUri") | .value' packaged.yaml) \
            s3://juanfunctions-us-east-1/s3.zip

